name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build project
        run: yarn build

      - name: Deploy with gh-pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.name "github-actions-bot"
          git config --global user.email "support+actions@github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx gh-pages -d dist -f
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
